/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.formula1.app;


import it.unicam.cs.formula1.api.Circuito.ICircuito;
import it.unicam.cs.formula1.api.Gara.Gara;
import it.unicam.cs.formula1.api.Giocatori.GiocatoreUmano;
import it.unicam.cs.formula1.api.Giocatori.IGiocatore;
import it.unicam.cs.formula1.api.Importer.BotImporter;
import it.unicam.cs.formula1.api.Importer.CircuitoImporter;
import it.unicam.cs.formula1.api.Gara.ViewGara;

import java.io.IOException;
import java.util.List;

public class Main {
    public static void main(String[] args) throws IOException {
        // Controlla se è stato passato almeno un argomento
        if (args.length < 2) {
            System.out.println("Usage: gradle run --args=\"<path-to-track-file> <path-to-bot-players-file>\"");
            return;
        }

        // Estrae i percorsi dai parametri passati
        String percorsoTracciato = args[0];
        String percorsoGiocatoriBot = args[1];

        // Importa il tracciato
        ICircuito circuito = CircuitoImporter.importaCircuito(percorsoTracciato);
        if (circuito == null)
            System.out.println("Errore durante l'importazione del circuito.");


        // Importa i giocatori bot
        List<IGiocatore> giocatori = BotImporter.importaBot(percorsoGiocatoriBot);
        if (giocatori != null) {
            GiocatoreUmano martina = new GiocatoreUmano('M');
            giocatori.add(martina); // Aggiungiamo il giocatore umano
        } else {
            System.out.println("Errore durante l'importazione dei giocatori bot.");
            return;
        }

        // Crea la Gara
        Gara partitaFormula1 = new Gara(circuito, giocatori); // Passa null per GaraView per ora

        // Crea l'oggetto ViewGara
        ViewGara garaView = new ViewGara(partitaFormula1);
        partitaFormula1.setViewGara(garaView);

        partitaFormula1.avviaGara(); // Avvia la gara
    }
}
