/*
 * MIT License
 *
 * Copyright (c) 2024 Martina Colibazzi
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.formula1.app;


import it.unicam.cs.formula1.app.Circuito.ICircuito;
import it.unicam.cs.formula1.app.Gara.Gara;
import it.unicam.cs.formula1.app.Gara.ViewGara;
import it.unicam.cs.formula1.app.Giocatori.GiocatoreUmano;
import it.unicam.cs.formula1.app.Giocatori.IGiocatore;
import it.unicam.cs.formula1.app.Importer.BotImporter;
import it.unicam.cs.formula1.app.Importer.CircuitoImporter;

import java.io.IOException;
import java.util.List;

public class Main {
    public static void main(String[] args) throws IOException {
        // Controlla se è stato passato almeno un argomento
        if (args.length < 2) {
            System.out.println("Usage: gradle run --args=\"<path-to-track-file> <path-to-bot-players-file>\"");
            return;
        }

        // Estrae i percorsi dai parametri passati
        String percorsoTracciato = args[0];
        String percorsoGiocatoriBot = args[1];

        // Importa il tracciato
        ICircuito circuito = CircuitoImporter.importaCircuito(percorsoTracciato);
        if (circuito == null)
            System.out.println("Errore durante l'importazione del circuito.");


        // Importa i giocatori bot
        List<IGiocatore> giocatori = BotImporter.importaBot(percorsoGiocatoriBot);
        if (giocatori != null) {
            GiocatoreUmano martina = new GiocatoreUmano('M');
            giocatori.add(martina); // Aggiungiamo il giocatore umano
        } else {
            System.out.println("Errore durante l'importazione dei giocatori bot.");
            return;
        }

        // Crea la Gara
        Gara partitaFormula1 = new Gara(circuito, giocatori); // Passa null per GaraView per ora

        // Crea l'oggetto ViewGara
        ViewGara garaView = new ViewGara(partitaFormula1);
        partitaFormula1.setViewGara(garaView);

        partitaFormula1.avviaGara(); // Avvia la gara
    }
}
