/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.formula1.app;


import it.unicam.cs.formula1.api.Circuito.ICircuito;
import it.unicam.cs.formula1.api.Gara.Gara;
import it.unicam.cs.formula1.api.Giocatori.GiocatoreBot;
import it.unicam.cs.formula1.api.Giocatori.GiocatoreUmano;
import it.unicam.cs.formula1.api.Giocatori.IGiocatore;
import it.unicam.cs.formula1.api.Importer.BotImporter;
import it.unicam.cs.formula1.api.Importer.CircuitoImporter;

import java.io.IOException;
import java.util.List;

public class Main {
    public static void main(String[] args) {
        ICircuito circuito = null;

        //importa tracciato
        try {
            CircuitoImporter importerCircuito = new CircuitoImporter();
            circuito = importerCircuito.importaCircuito("src/main/java/it/unicam/cs/formula1/app/circuito.txt");
        } catch (IOException e) {
            System.err.println("Errore durante l'importazione del circuito: " + e.getMessage());
        }

        GiocatoreUmano martina = new GiocatoreUmano('M');
        List<IGiocatore> giocatori = null;

        //importa giocatori bot
        try {
            BotImporter importerBot = new BotImporter();
            giocatori = importerBot.importaBot("src/main/java/it/unicam/cs/formula1/app/giocatori_bot.txt");
        } catch (IOException e) {
            System.err.println("Errore durante l'importazione del circuito: " + e.getMessage());
        }

        giocatori.add(martina); //aggiungiamo il giocatore umano

        //creaiamo la gara
        Gara partitaFormula1 = new Gara(circuito, giocatori);
        partitaFormula1.stampaStatoGara(); //stampiamo lo stato iniziale della gara
        partitaFormula1.avviaGara(); //avviamo la gara

    }
}
